### PR TITLE
add route prefix config

### PR DESCRIPTION
**Pull request by The-Hasanov**

### CODE REVIEW

**Comment by ovanschie** [comment]
Why is this useful?

**Comment by The-Hasanov** [comment]
in my situation 
Nginx configration like this

Domain.com/ response  index.html for react application 

Domain.com/api/ production server

Domain.com/api-alpha/    alpha testing

**Comment by ovanschie** [comment]
can't you just set OPCACHE_URL=http://domain.com/api-alpha ?

**Comment by The-Hasanov** [comment]
but this change only requests routes still domain.com/opcache

**Pull request merged**
